### ISSUE TITLE
Negative value of Surface Tension SubSteps

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#417] opened 2019-01-25 09:56 UTC
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.2**
**Operating System: Windows 7 64 bit**
**CPU: A8 5600K 3.60GHz 4 Core**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug
Addon displays negative values in the tooltip near Surface Tension.

#### To Reproduce

Here is the scene:
[suf_tens_substeps.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2795554/suf_tens_substeps.zip)

#### Expected Behaviour

Sub-steps must be greater than zero.

#### Screenshots
![bug](https://user-images.githubusercontent.com/7983249/51738582-859c9b00-20a0-11e9-8c05-83991c9aa6ef.jpg)

**Comment by rlguy** [comment] 2019-01-25 19:59
Hi PavelBlend,

Thanks for the report, I just had a chance to check this out! The negative value was caused by a math error. This has been fixed will be included in the next update available next Friday (Feb 1st).

\- Ryan

**Closed by rlguy** 2019-01-25 19:59 UTC
