### ISSUE TITLE
Blender 2.80 crashes while rendering when whitewater particles are enabled.

### ISSUE THREAD

**Issue by rbx775** [rlguy/Blender-FLIP-Fluids#430] opened 2019-02-23 11:07 UTC
[ff_28.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2896723/ff_28.zip)

#### System Information

**Blender Version (including hash):** 2.80 - 790cb7799dcf
**FLIP Fluids Version:** Experimental feb 2019 - 9.0.5
**Operating System:** Win10
**CPU:** AMD Ryzen7 1800x
**GFX:** AMD Vega64
**RAM:** 16GB

#### Describe the bug

Blender2.8 crashes when trying to render fluid simulations of any kind WITH whitewater particles enabled.
True for every render mode, EEVEE/WORKBENCH/CYCLES. Animation or still.
It also doesnt matter if the whitewater particles have materials assigned or not.

#### To Reproduce

Create a Domain => Create body of fluid => activate "Enable Whitewater Simulation" in the Domain properties.

#### Expected Behaviour

No crash when rendering with whitewater particles.

#### Actual Behaviour

Blender Crashes, always after the first frame.

#### Screenshots

See .blend

**Comment by rbx775** [comment] 2019-02-23 11:21
I saw similiar bugreports suggesting "locking the Interface" and "changing windows to non-3D_view".
That didnt help, but:
**Rendering via commandline** seems to do the trick!
So thats a viable workaround in the meantime!

**Comment by rlguy** [comment] 2019-02-25 23:09
Hi rbx775,

Thanks for the report! I am able to reproduce this crash consistently. I assume that this is caused by a recent change in Blender 2.80 since rendering whitewater was possible in earlier versions. I'll investigate this further so that a report can be made to the Blender developers.

\- Ryan

**Comment by iad96** [comment] 2019-03-17 20:35
Has anyone found a solution to this problem? it keeps crashing using blender 2.8 :(

**Comment by rlguy** [comment] 2019-03-17 23:25
There is no solution or workaround that I know of, sorry. This bug is related to this issue #403. It has been reported to the Blender developers here: https://developer.blender.org/T60094 and the bug has been confirmed and set to 'Medium' priority.

It could be some time before a fix is made. There are a very large number of open bugs within Blender 2.80 that the developers are working on, but I'm sure they're working as hard as they can.

**Comment by semillerimages** [comment] 2019-03-27 19:29
Rendering on 2.8 with eevee crashes after around 6 frames consistently on one of my machines

**Comment by rlguy** [comment] 2019-03-27 19:36
Hi semillerimages,

This issue will have more details on the cause of EEVEE crashes: #403

It has been reported to the Blender developers here: https://developer.blender.org/T60094 and the bug has now been set to 'High' priority.

\- Ryan

**Comment by alex3dpl** [comment] 2019-04-07 11:47
Same on linux (Suse Tumbleweed) Eevee and Cycles. Still render sometimes works; animation render (two/three frames and crashes).

**Comment by rlguy** [comment] 2019-05-02 19:46
Update: after some testing with later versions of Blender 2.80, it looks like this issue is caused by exactly the same problem detailed in issue #403. I will be closing this issue #403 will continue as the main issue thread.

**Closed by rlguy** 2019-05-02 19:46 UTC
Labels: Blender 2.80, bug, crash
