### ISSUE TITLE
not be able to bake an 32 resolution

### ISSUE THREAD

**Issue by dpotuznik** [rlguy/Blender-FLIP-Fluids#625] opened 2023-09-23 15:49 UTC
#### System and Blend File Information

**Blender Version:** 3.5.1, octane2022_Blender3.5, 2023-05-17 11:23, 71fffab9dc8a
**Addon Version:** A FLIP Fluid Simulation Tool for Blender (v1.7.1 Stable 25-JUL-2023)
**OS:** Windows-10-10.0.22621-SP0
**GPU:** NVIDIA GeForce RTX 3090/PCIe/SSE2 NVIDIA Corporation 4.5.0 NVIDIA 531.61
**CPU:** 12th Gen Intel(R) Core(TM) i9-12900K
**CPU Threads:** 24
**RAM:** Unknown (fill in)

**Blender Binary:** C:\Program Files\BlenderOctane\blender.exe
**Addon Path:** C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon
**Renderer:** CYCLES
**Cycles Device:** GPU
**Viewport Modes:** SOLID
**Objects:** 21
**FLIP Objects:** 3
**FLIP Domains:** Domain <scene: Scene>
**Obstacle Objects:** 1 <Export Animated: 1> <Skip Re-export: 0>
**Fluid Objects:** 1 <Export Animated: 0> <Skip Re-export: 0>
**Inflow Objects:** 0
**Outflow Objects:** 0
**Force Objects:** 0
**Cache Path:** G:\Unreal\MetaTribesMaps53\Document\Cinematic\blender\testFluidV2
**Cache Exists:** True
**Cache Logs:** 7
**Simulation Visibility:** <Viewport: Enabled> <Render: Enabled>
**Surface Visibility:** <Viewport: DISPLAY_FINAL> <Render: DISPLAY_FINAL>
**Whitewater Visibility:** <Viewport: DISPLAY_FINAL> <Render: DISPLAY_FINAL>
**Enabled Features:** Whitewater
**Enabled Attributes:** N/A
**Lock Interface:** Enabled
**Cycles Persistent Data:** Disabled
**Developer Tools:** Enabled
**Mixbox Plugin:** Installed
**Enabled Addons:** Bool Tool, Align Tools, tinyCAD Mesh tools, LoopTools, Edit Mesh Tools, blender-osm, RizomUV Bridge, Node Wrangler, 3D-Print Toolbox, Adobe Substance 3D add-on for Blender, 3D Viewport Pie Menus, OctaneBlender (v. 27.16), Octane Helper, Copy Attributes Menu, Export: Adobe After Effects (.jsx), Sanctus-Library, MESHmachine, Xolotl Substance Painter Live Link, Quad Remesher 1.2 Bridge, Game Rig Tools - Unreal Module, FLIP Fluids 1.7.1

#### Describe the bug

When I launch the bake I have an error after few second is not begin the simulation it calculate the mesh animation 
after about 10% i receive this error
Python: Traceback (most recent call last):
  File "C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon\operators\export_operators.py", line 149, in modal
    is_finished = self.geometry_exporter.update_export(self.export_step_time)
  File "C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 134, in update_export
    raise e
  File "C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 124, in update_export
    self._process_work_item(work_item)
  File "C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 484, in _process_work_item
    self._process_mesh_object(work_item)
  File "C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_exporter.py", line 415, in _process_mesh_object
    self._geometry_database.add_mesh_animated(object_id, frame_id, bobj_data)
  File "C:\Users\feeble\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\flip_fluids_addon\objects\flip_fluid_geometry_database.py", line 195, in add_mesh_animated
    self._cursor.execute(insert_command, values)
sqlite3.OperationalError: attempt to write a readonly database

simple rising robot , I use the flip remesher 
<img width="827" alt="image" src="https://github.com/rlguy/Blender-FLIP-Fluids/assets/11964995/c9448869-b4df-4d0b-9a7b-278ef245a056">

**Comment by rlguy** [comment] 2023-09-24 17:01
Thanks for the report! This looks like a duplicate of issue #617 which we are looking for feedback on. Would you be able to test the proposed solutions and let us know what did and did not work for your in the other thread?

**Closed by rlguy** 2023-09-24 17:01 UTC
