### ISSUE TITLE
Blender 2.8 fluid shape bug

### ISSUE THREAD

**Issue by alex3dpl** [rlguy/Blender-FLIP-Fluids#442] opened 2019-04-07 11:37 UTC
#### System Information

Blender Version (including hash): 2.8 2019-04-06 cc73d59ad580 
FLIP Fluids Version: 9.0.5.3 experimental 01-FEB-2019
Operating System: Suse Tumbleweed 64-bit
CPU: AMD FX-4100
GFX: GTX 960 4GB
RAM: 8GB

#### Describe the bug
Strange fluid shape (like rotated 45 degrees)
#### To Reproduce

Add domain cube, add fluid (a half domain size)

#### Expected Behaviour

Full fluid shape.

#### Screenshots
![FF_bug](https://user-images.githubusercontent.com/36315575/55682937-3691a280-593a-11e9-87d6-771bb75112d4.jpg)

**Comment by rlguy** [comment] 2019-04-07 16:54
Thanks for the report! It looks like this issue is caused by a recent change in Blender 2.80. The object shape works as expected in older versions of Blender 2.80.

I suspect that there might be a bug in how Blender is exporting meshes. This is how the mesh is being exported in the most recent version:

![exported_mesh](https://user-images.githubusercontent.com/4285191/55686821-e0613700-591a-11e9-9d13-23ac1e57b0d9.jpg)

I'll be able to look further into this after the weekend.

**Comment by rlguy** [comment] 2019-04-08 18:44
I have had a chance to take a look at this issue. It looks like the problem is that in a recent version of Blender 2.80, modifiers added to an object by a script/addon are not being applied before converting the object to a mesh. 

The FLIP Fluids simulator requires that the mesh polygons consists of only triangles. We do this by adding a Triangulate Modifier when exporting the object for the simulator. Since the modifier was not applied, the resulting mesh geometry was not correct.

I have found a workaround that seems to fix this within the addon. I will continue testing this workaround to make sure that it works in future versions of Blender 2.80. This issue might fix itself in future versions.

### Workaround 1: editing addon script

Until we release a new version, a workaround is to replace a script within the FLIP Fluids addon.

Replace the ```Blender 2.80/scripts/addons/flip_fluids_addon/utils/version_compatibility_utils.py``` script with this updated file: [version_compatibility_utils.py](https://pastebin.com/tGcjMW7n)

### Workaround 2: add triangulation modifier manually

An alternative to editing the scripts is to add a Triangulation Modifier to the fluid/inflow/outflow/obstacle objects before baking the simulation.

**Comment by EntitySelf** [comment] 2019-04-14 15:02
The first workaround worked for me, thank you.

**Comment by rlguy** [comment] 2019-05-02 19:34
It looks like this issue will be a permanent change in Blender 2.80. It's a simple fix/modification on our side and we will be including this fix in the next experimental version (9.0.5.4) which will be available near the end of next week.

**Closed by rlguy** 2019-05-02 19:34 UTC
Labels: Blender 2.80, bug
