### ISSUE TITLE
Particle Jitter works only for the first frame

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#435] opened 2019-03-23 10:21 UTC
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5.3**
**Operating System: Windows 7 64 bit**
**CPU: AMD A8 5600K 3.60 GHz**
**GFX: -**
**RAM: 8 GB**

#### Describe the bug

Particle Jitter works only for the first frame.

#### To Reproduce

Start baking this scene:
[particle_jitter.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2999211/particle_jitter.zip)

#### Expected Behaviour

It is necessary that the born particles have a random position.

#### Actual Behaviour

In the first frame, the particles are arranged randomly:
![00](https://user-images.githubusercontent.com/7983249/54864875-52a81800-4d6e-11e9-8317-d7fb3519689c.jpg)

But in the subsequent frames there is no randomness:
![01](https://user-images.githubusercontent.com/7983249/54864878-59cf2600-4d6e-11e9-8deb-6586a326e08c.jpg)

**Comment by rlguy** [comment] 2019-03-25 19:29
Hey PavelBlend,

Thanks for the report and .blend file! I was able to reproduce the issue.

This is caused by a side effect of how particles are added within a mesh:
- Particles are only added to empty space within the object. This is to avoid adding extra particles that overlap other particles.
- Particles are only jittered inside the mesh object. Particles that are closer to the surface are not jittered. This is to produce a smoother and less random/bumpy shape when meshing.

Here is an explanation for what is happening. 

**Frame 1:** particles are added according to the above rules. While simulating the next frame, the top surface particles that are aligned to the grid (outlined in red) will move down according to gravity and inflow velocity.

![frame1](https://user-images.githubusercontent.com/4285191/54947623-fbce4a00-4ef7-11e9-9fa3-2e1f565ba1e1.jpg)

**Frame 2:** Since the grid aligned particles have moved downwards, no new particles will be emitted in the red outlined area. So no jittered particles will be added.

![frame2](https://user-images.githubusercontent.com/4285191/54947626-fc66e080-4ef7-11e9-918e-f1e7b933dc83.jpg)

Note: the 'Constrain Inflow Velocity' option will make the particles move downwards within the inflow very ordered and without much variation in motion. If you disable this option, particles move around more chaotically and you will have empty space and more jittered particles emitted:

![jittered_unconstrained](https://user-images.githubusercontent.com/4285191/54948085-15bc5c80-4ef9-11e9-9431-b5187ae20c0c.jpg)

### Fixing this issue

To fix this issue and guarantee that all emitted particles are jittered, the surface particles should also be jittered. An option should be added to the [Advanced Panel](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Advanced-Settings#simulation-stability) to set whether or not surface particles should be jittered.

I'll set this issue as a feature request for this option.

Hope this explains the issue well!

\- Ryan

**Comment by rlguy** [comment] 2019-04-08 20:30
I have added this as an option:

![jitter_option](https://user-images.githubusercontent.com/4285191/55754786-5391a880-5a02-11e9-90c1-65bca397bf1c.jpg)

![jitter_result](https://user-images.githubusercontent.com/4285191/55754787-5391a880-5a02-11e9-9564-9444ae36f9b6.jpg)

This will be included in the next version update.

**Closed by rlguy** 2019-04-08 20:30 UTC
Labels: bug, feature
