### ISSUE TITLE
Unable to compile on m2 mac arm

### ISSUE THREAD

**Issue by Shubhankitj** [rlguy/Blender-FLIP-Fluids#608] opened 2023-03-01 16:33 UTC
I can’t compile the addon on Mac OS pls someone help I can’t get cmake or python or gnumake to work.

**Comment by rlguy** [comment] 2023-03-01 16:54
Hi, you may want to search for a guide on how to install or use CMake, Python, and GNU Make. Note that the [build instructions](https://github.com/rlguy/Blender-FLIP-Fluids#building) mention that some programming experience or prior experience building C/C++ applications is recommended.

Please note that this issue tracker is only meant for issues/bugs related to the Blender Market version of the FLIP Fluids addon. We are also unable to provide support for building and diagnosing issues related to building the addon on the wide variety of systems and system setups, and development experience.

Duplicate of https://github.com/rlguy/Blender-FLIP-Fluids/issues/511

**Closed by rlguy** 2023-03-01 16:54 UTC
