### ISSUE TITLE
Render Animation Problem

### ISSUE THREAD

**Issue by rgelmi** [rlguy/Blender-FLIP-Fluids#480] opened 2019-11-12 20:58 UTC
The plugin work but i cant render the animation of fluid. The Blender close. 

Blender Version: Blender 2.8
FLIP Fluids Version: 1.0.6
Operating System: macOS Hight Sierra 10.13.6
CPU: Intel i7-7700 @ 3.60GHz
GFX: AMD FirePro D700 6144 MB
RAM: 64 GB 1866 MHz DDR3

**Comment by rlguy** [comment] 2019-11-12 21:02
Hi, this is a duplicate of https://github.com/rlguy/Blender-FLIP-Fluids/issues/403#issuecomment-539727971

To prevent render crashes, you will need to lock the Blender Interface (**Blender > Render > Lock Interface**). [Blender 2.81](https://builder.blender.org/download/) is required to fully prevent render crashes due to a bug in Blender 2.80.

**Closed by rlguy** 2019-11-12 21:02 UTC
