### ISSUE TITLE
Issues exporting simulation meshes with large number of vertices/triangles

### ISSUE THREAD

**Issue by Leumeister** [rlguy/Blender-FLIP-Fluids#357] opened 2018-07-11 16:22 UTC
#### System Information

**Blender Version (including hash): 2.79 (f4dc9fd68b)**
**FLIP Fluids Version 1.0.2:**
**Operating System: Windows 10 Home (64-bit)**
**CPU: Intel(R) Core(TM) i7-4790**
**GFX: Nvidia GeForce GTX 1080 ti**
**RAM: 32 Gigabytes**

#### Describe the bug

Exporting animation data on rigged characters takes a very long time, and eventually crashes the Blender instance. Done on the CPU, as I hadn't enabled GPU usage at the time.

#### To Reproduce

Create a fluid scene with inflow object, allow it to fill a mesh basin. Then animate a character interacting with the fluid, specifically a character made of individual parts, either joined or separate objects, controlled by armature with vertex weights. Bake.

#### Expected Behaviour

Simulation bakes, taking as long as it needs, and then plays back as expected.

#### Actual Behaviour

Simulation will hang on "exporting animated data" for a long time, and will eventually crash Blender.
[David_Av_discovery.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2185346/David_Av_discovery.zip)

**Comment by rlguy** [comment] 2018-07-12 00:58
Hello,

Thanks for reporting this. I can confirm the crash. This looks like a complicated scene and I will be able to look further into what could be causing this issue tomorrow. I'll keep you updated in this thread!

\- Ryan

**Comment by Leumeister** [comment] 2018-07-12 03:58
@rlguy 
Thank you. :) I appreciate your help! ^_^

**Comment by rlguy** [comment] 2018-07-12 21:40
Hello Leumeister,

I just had a chance to take a further look at what is going on in the .blend file. The problem is that your simulation meshes are very very large (in vertices/triangles). These meshes end up being too large for Blender to handle and that is why exporting the simulation takes so long and ends up crashing. The mesh sizes would also be too large for the simulator to handle if the export ended up successful. The simulator does not need this high level of detail for your meshes.

Here are some details on the problem meshes:

### Cube.011 and Cube.023

Each of these meshes are animated and each contain 3.3 Million vertices and 3.3 Million triangles. This ends up being about 150MB of mesh data for each mesh **per frame**. Over the entire animation, that is a combined total of **354GB** of mesh data.

### NobleHau and NobleHau.001

These meshes are not marked as animated simulation objects in the scene, but it looks like you might want these animated. I am not sure. To animate these objects, you will need to check the 'Export Animated Mesh' option.

Each of these meshes contain 1.8 Million vertices and 3.6 Million triangles. This ends up being 59MB of mesh data for each mesh. If animated, this would be a combined total of **139GB** of mesh data.

### Lair

This one is not that large of a problem since this object is not animated. This mesh contains 430 Thousand vertices and 843 Thousand triangles. The simulator does not require this amount of detail in a mesh, but it would still be able to handle an obstacle of this size as long as it is not animated.

---

The main contributor to mesh size in your scene are the __Subdivision Surface__ modifiers. These are adding a lot of triangles to each mesh. Removing these modifiers significantly reduces the amount of vertices/triangles in the meshes and speeds up the export process. Without any further modification to the scene, the meshes are still quite large for use in a simulation and could result in a very long simulation time.

Here are some additional tips that might help with the scene:
- Some of your obstacles are quite thin. Here are some tips on how to handle simulations with thin obstacles: [Scene Troubleshooting: Thin obstacles, leaking fluid](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#thin-obstacles-leaking-fluid)
- Make sure that all of your objects are [Manifold](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Manifold-Meshes). Simulating with non-manifold objects can result in an unpredictable simulation. I see that some objects use an edge split modifier. The edge split modifier will often split edges which create non-manifold objects.

I hope that this helps!

\- Ryan

**Comment by Leumeister** [comment] 2018-07-13 04:20
Ah... Okay...
I'm not sure edgesplit is being used, but I'll get rid of them. And I'll turn off the subdivision surface, and see if that works.

**Comment by Leumeister** [comment] 2018-07-13 12:37
Hey! The animated data is exporting a lot faster now! Thanks for your help! 👍

**Comment by rlguy** [comment] 2018-07-13 18:22
No problem, that's great to hear!

**Closed by rlguy** 2018-07-13 18:22 UTC
Labels: crash, scene troubleshooting
