### ISSUE TITLE
Exporting preset package: error overwriting existing file

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#320] opened 2018-05-27 14:19 UTC
Hi Ryan, while updating the library i was not able to overwrite the ZIP-Package.
A message "this will overwrite an existing file" would be required.

https://i.imgur.com/M8WJ3lH.png

**Comment by rlguy** [comment] 2018-06-01 23:49
Hey, I wasn't able to reproduce and get this error message. Are you able to export the zip package properly when using a new file name? The error might be caused by the addon not having permission to overwrite the file in that directory. I am wondering: Are you able to export the package and overwrite files on your desktop folder where the addon has full permissions? 

I'll get the addon to detect this error and display a user friendly popup message.

**Comment by rlguy** [comment] 2018-06-10 19:39
The addon will now display a popup error message if it is unable to write the exported file. This change will be included in the next version update (**1.0.4**).

![export_error](https://user-images.githubusercontent.com/4285191/41205597-45beafb8-6cab-11e8-9339-f67d89284312.jpg)

**Closed by rlguy** 2018-06-10 19:39 UTC
