### ISSUE TITLE
Incorrect fluid creation

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#557] opened 2021-09-18 13:43 UTC
#### System Information

**Blender Version (including hash):** 2.93.4 rBb7205031cec4
**FLIP Fluids Version:** v9.1.1 experimental 17 sep 2021
**Operating System:** win10 64 bit
**CPU:** AMD A8 5600K
**GFX:** -
**RAM:** 16 GB

#### Describe the bug

Incorrect fluid creation:
![01](https://user-images.githubusercontent.com/7983249/133890866-7dece658-d9da-4c25-a9f2-e534cb850a3b.jpg)

If you split the fluid mesh into parts, then the fluid will be correct.
![02](https://user-images.githubusercontent.com/7983249/133890899-fe45eeb9-1fbf-4135-a10d-58edbde540b4.jpg)

blend-file:
[fluid_engine_dev_example.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/7189976/fluid_engine_dev_example.zip)

**Comment by rlguy** [comment] 2021-09-20 01:59
Thanks for the report and .blend file! I am able to reproduce this issue.

It looks like the bug is that the simulator is simplifying the mesh into a single cube object, which is incorrect in this case. This has been fixed and will be included in the next experimental release v9.1.2, date TDB.

![image](https://user-images.githubusercontent.com/4285191/133950837-ce3f1baf-deaf-4f93-b5b7-43fcef42d843.png)

**Closed by rlguy** 2021-09-20 01:59 UTC
Labels: bug
