### ISSUE TITLE
Crash during animation (Random) between the end of a frame and the successive ones.

### ISSUE THREAD

**Issue by Blenderari** [rlguy/Blender-FLIP-Fluids#391] opened 2018-10-03 20:54 UTC
I'm having the same issue.
I'm using Flip Fluid a lot and I'm very very happy with it :)
But I'm having a weird issue with my last animation.
Rendering the animation, sometimes, not always, just sometimes and randomly (If i try to render the same frame the second times it works....) When I rendered a frame, just after few second, during the preparation for the next frame, Blender crash and it close itself.....
If I reopen the scene, it works fine until, randomly, it crash between some other frames rendering.....the crash always happen the end of a frame and the start of the successive....

My pc is composed by

Xeon 2695V3
32gb ram
3x quadro P4000
Windows 7 pro

my blender version is the official 2.79 and the flip fluid version is the last one

The crashes always seem to happen either just after a frame finishes rendering, or right as the next one starts, and the frame is not the issue because if i try to render it again it works and it will crash after some other random frames.

Thanks for any help

_Originally posted by @Blenderari in https://github.com/rlguy/Blender-FLIP-Fluids/issues/328#issuecomment-426798162_

**Comment by rlguy** [comment] 2018-10-03 20:57
Hello Blenderari,

Thanks for the report! Does [this workaround](https://github.com/rlguy/Blender-FLIP-Fluids/issues/323#issuecomment-393563990) prevent crashes for you?

\- Ryan

**Comment by Blenderari** [comment] 2018-10-03 22:35
Hi,
I've just tried it and after 9 frames it happened again.... :(

and again...it ended well and during the switching to the next ones..Blender closed itself..

The error was "Exception access violation"

**Comment by Blenderari** [comment] 2018-10-03 22:51
I attach here the memory usage display, maybe it can been of help.....I;ve tried to write some notes on it :)
![senza titolo-1](https://user-images.githubusercontent.com/40810317/46443833-887d2400-c76f-11e8-85a8-f326dcb29d7b.jpg)

**Comment by rlguy** [comment] 2018-10-04 00:19
Hey, thanks for the update. Sorry to hear that the workaround is not preventing the crashes!

I am wondering if rendering from the command line would help prevent crashes. This is the most stable way to render a large simulation. I have just added documentation for how to do this here: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Rendering-from-the-Command-Line

Would it be possible to attach a .blend file of your scene for me to take a look at? This will give me more information on the type of simulation and render settings. Alternatively, you may send the .blend file to _flip.fluids@gmail.com_.

\- Ryan

**Comment by Blenderari** [comment] 2018-10-04 13:37
Hi Ryan,
No need of being sorry.....Flip Fluid is GREAT! I think is normal to have some bug/problems at the beginning...... ;)

Thanks to you for trying to help me....I love the plugin and i love that the plugin creator is available to chat directly with us! i really do!

I'm sending the scene right now to you via wetransfer at the address you provided to me :)

Thanks!

P.S. the setting that are inside the file have been used for other two flip fluid simulation and they worked fine.....just in this file,I'm having problem....maybe could be a messed up baking session?

Have a good day
;)

**Comment by Blenderari** [comment] 2018-10-04 13:41
Please forgive me about my poor english....

**Comment by rlguy** [comment] 2018-10-04 21:13
Hey Blenderari,

Thanks for attaching the scene! None of the settings look like they could be causing crashes, so I'm not 100% certain what is the cause of the crashes.

These render crashes are common for users and they all seem to occur at the end of a frame between unloading the frame and loading the next frame. Some users experience these crashes regularly, and some users never experience these crashes. It seems to depend on the hardware of the user, and unfortunately I am never able to reproduce these crashes so it is quite a tricky issue to debug! It seems like the frequency of these crashes increases depending on how much geometry there is in the fluid meshes, so it could be possible that you are seeing these crashes due to rendering larger simulation.

I have looked around the Blender bug tracker and have seen a few related issues of crashes during animation that might be the cause of this bug. The problem looks like Blender is trying to access memory which does not exist anymore (perhaps right after a frame is unloaded) which is what the _EXCEPTION_ACCESS_VIOLATION_ error means.

Here are a few things that you could try:

---

1. Try [rendering from the command line](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Rendering-from-the-Command-Line) to see if the scene renders with more stability.

---

2. Try closing the multiple Blender windows and render with a single window using the [full screen render workaround](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#blender-often-crashes-suddenly-or-does-not-apply-transforms-while-rendering).

I noticed in your .blend file that you are running three Blender windows. I am not sure if this will work, but it is possible that rendering from a single window might help prevent crashes. 

Reason: The 'full screen' workaround was mentioned by a Blender developer. The purpose of setting the render to full screen was to remove the UI menus and viewport from the interface during rendering. The developer mentioned that the crashes might be occurring when Blender updates the UI menus or viewport and removing these from the window stops Blender from making these updates. It might be possible that having multiple windows open is preventing the workaround from stopping UI/viewport updates.

---

3. Try recreating your scene in a new .blend file. We have had a report that a user stopped experiencing crashes by recreating their scene in a new .blend file.

It is not necessary to re-bake the simulation. You can create a new domain object and set the [Cache Directory](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Domain-Cache-Settings#parameters) to your already baked cache directory. The addon will use this directory to load the meshes during playback.

---

And your English is perfectly fine!

\- Ryan

**Comment by Blenderari** [comment] 2018-10-09 16:10
HI,
First of all, thanks for your time and the precious advices.
I've seen a huge stability improvement closing all the multiple blender windows.......it seems working quite fine right now :)

**Comment by rlguy** [comment] 2018-10-09 21:02
Thanks for the update, that's great to hear! I have added a note to close multiple windows on the render workaround topic.

\- Ryan

**Closed by rlguy** 2018-10-09 21:02 UTC
Labels: crash
