### ISSUE TITLE
Bake Error: AttributeError: 'array.array' object has no attribute 'tostring'

### ISSUE THREAD

**Issue by Gh0stXE** [rlguy/Blender-FLIP-Fluids#562] opened 2021-11-14 22:04 UTC
Whenever I try to bake it gives me [Errno 2] No such file or directory: 'D:\\IDFK\\untitled_flip_fluid_cache\\export\\flipdata.sim'. See system console for error info.
 when I check my files 
![fuck](https://user-images.githubusercontent.com/94324503/141700383-1c65f7f0-1be0-4982-a59b-6670235d01b2.png)
 I get this please help me out

**Comment by rlguy** [comment] 2021-11-14 23:34
Thanks for the report! Would you be able to attach a full error message from the Blender System Console, your system and version information, and a basic .blend file that reproduces the issue? This will help us reproduce the error so that we can look into the issue.

See: [Guidelines for Reporting Bugs and Issues](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues).

**Comment by Gh0stXE** [comment] 2021-11-15 07:14
There really isnt a spesific blend file it happens with any project but I can send i
![ERROR](https://user-images.githubusercontent.com/94324503/141737243-1b901139-3363-4f79-b908-cee42573481e.png)
t
![ERRORNO](https://user-images.githubusercontent.com/94324503/141737265-d5f7dad9-3885-421b-adda-f18ff7dd3225.png) 
and here is the file https://www27.zippyshare.com/v/YtIYQCn9/file.html

**Comment by Gh0stXE** [comment] 2021-11-15 10:46
> Thanks for the report! Would you be able to attach a full error message from the Blender System Console, your system and version information, and a basic .blend file that reproduces the issue? This will help us reproduce the error so that we can look into the issue.
> 
> See: [Guidelines for Reporting Bugs and Issues](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Guidelines-for-Reporting-Bugs-and-Issues).

I hope I provided the rigth documents so you can solve the problem

**Comment by rlguy** [comment] 2021-11-15 19:24
Duplicate of issue #553

Thanks for the update! You will need to update to a more recent version of the FLIP Fluids addon (v1.0.9b (06-APR-2021)  or later) which adds compatibility support for Blender 2.93. 

More info in this issue: https://github.com/rlguy/Blender-FLIP-Fluids/issues/553#issuecomment-913188408

**Closed by rlguy** 2021-11-15 19:24 UTC
Labels: duplicate
