### ISSUE TITLE
Material duplication when adding presets to stack

### ISSUE THREAD

**Issue by dafassi** [rlguy/Blender-FLIP-Fluids#365] opened 2018-07-29 16:03 UTC
Hi Ryan, while improving the materials/presets library i often have problems with duplicated materials (that will be saved in our material-file).
What i found out is:
If there still are materials for surface/whitewater in the materials-panel and then we add a preset to the stack it will not replace the materials in the materials panel. It adds them. Can we fix this?

Without preset (but materials are already choosen): 
https://i.imgur.com/MDiwE4W.png

WITH preset added:
https://i.imgur.com/rjH6tdl.png

**Comment by rlguy** [comment] 2018-08-05 20:39
Hey Dennis,

Apologies for the late reply! Unfortunately duplicated materials are unavoidable. This is related to issue #321. We are unable to compare if two materials are equal, so when we import a preset or material from the material library, Blender will create a duplicate of the material. And if the material has the same name, it will add a number to avoid duplicate names.

For editing the material library, I think a workaround would be to manually delete and rename material duplicates. To avoid presets from creating duplicate material name when editing, I think the workaround would be to delete all materials in the scene.

Maybe in the future I'll be able to rewrite the material library and presets to use a better system, but this is quite a bit of work right now. It turns out that the code becomes quite complex and I guess that is why there are entire add-ons devoted to material library management!

\- Ryan

**Closed by rlguy** 2018-08-05 20:39 UTC
