### ISSUE TITLE
I can't bake the fluid 

### ISSUE THREAD

**Issue by Nemoide** [rlguy/Blender-FLIP-Fluids#553] opened 2021-09-05 06:06 UTC
Hi, i have this issue, any help is good received, thanks
![image](https://user-images.githubusercontent.com/90126160/132117225-8de322a4-e1b7-409d-ba29-ec8bde6c5005.png)

**Comment by rlguy** [comment] 2021-09-05 16:47
Hi, this error means that you will need to update the FLIP Fluids addon to a newer version which adds support for Blender 2.93.

More info in [Installation Troubleshooting](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Addon-Installation-and-Uninstallation#baking-error-attributeerror-arrayarray-object-has-no-attribute-tostring)

> **Baking Error: AttributeError: 'array.array' object has no attribute 'tostring'**
> If you are receiving this error message in Blender 2.93 or later, this will indicate that there is a compatibility error between your installed FLIP Fluids addon version and installed Blender version. You will need to update your FLIP Fluids addon version to v1.0.9b (06-APR-2021) or later. This version of the FLIP Fluids addon adds compatibility support for Blender 2.93+.

Issue is a duplicate of #525.

**Closed by rlguy** 2021-09-05 16:47 UTC
