### ISSUE TITLE
new view layer causes crash 2.8

### ISSUE THREAD

**Issue by chienMouille** [rlguy/Blender-FLIP-Fluids#468] opened 2019-07-24 17:34 UTC
#### System Information

**Blender version: 2.8 (b63f0266a056):**
**FLIP Fluids Version: v9.0.6.0**
**Operating System: MacOsX 10.14.5**
**CPU:2.6 GHz Intel Core i7**
**GFX:Radeon Pro Vega 20 4 GB Intel UHD Graphics 630 1536 MB**
**RAM:32 GB 2400 MHz DDR4**

#### Describe the bug

Blender crashes systematically when clicking on "New view layer" button.
It also crashes often when triggering "Undo".

#### To Reproduce

Click on the "new view layer" button on top of the collection window.

#### Expected Behaviour

a new view layer would be created

#### Actual Behaviour

blender crashes and quits

#### Screenshots

<img width="535" alt="Screen Shot 2019-07-24 at 13 31 58" src="https://user-images.githubusercontent.com/38041299/61815151-96438900-ae17-11e9-949b-be9fc6328bcd.png">

**Comment by rlguy** [comment] 2019-07-24 17:45
Hi chienMouille,

Thanks for the report! I just had a chance to test this, but was not able to reproduce the crash. I am only available to test on Windows at the moment, so this may be an issue specific to MacOS.

Would you be able to attach a .blend file that reproduces this issue so I can test this?

If you disable the FLIP Fluids addon in the user preferences and try to add a new view layer in your .blend file, do you still experience the crash?

\- Ryan

**Comment by chienMouille** [comment] 2019-07-24 17:56
Attachment available until 23 Aug 2019
Hi Ryan,

I did a bit more testing:
when flip fluid add-on is disabled, the bug still occurs.

However, I identified now that the cause of the crash seems to be the object “Cube”, just below the camera in the main collection.
Once deleted I’m able to create a view layer.
Trying to trigger its view port visibility is also causing blender to crash.

Attached is the file, so you can test.

Let me know!


bastien


Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FATyRfY8Yw6H3PK2BD98uITL6XN5SAWX0hJ7LzYLTcvq1s6ihI18z_DIM%2F%24%7Bf%7D%3Fo%3DAlvZqq3vZ3MCTjZVNDcSlAzowTZIbzvD6_W4MIVRjHjr%26v%3D1%26x%3D3%26a%3DCAogZAlxhmHrGax6U7C-p6LnEYJzkrRJVnsB4zcu7mokMfoSJxDiroCpwi0Y4r77_MstIgEAKggByAD_fORWB1IE-lzeUloEM_wyDA%26e%3D1566582955%26k%3D%24%7Buk%7D%26fl%3D%26r%3D0A5DE725-EDE3-4C43-B482-BC2FA6CD357A-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DA2354406-D675-4A52-88B4-FD46A17D31AF%26p%3D59%26s%3DCfpNyFN-voDQqMTyI1tZjpRxuek&uk=bw_wNpotX3T4YF6qBvhp5w&f=socket9_liquid.blend&sz=22457216>socket9_liquid.blend
22.5 MB

**Comment by rlguy** [comment] 2019-07-24 18:05
Thanks for the .blend file! I am able to reproduce the crash with this file using Windows. I am also able to reproduce the crash when the FLIP Fluids addon is disabled.

Since this crash occurs without the addon, this will be an issue within Blender 2.80 that the Blender developers will need to fix, so I will be closing this issue thread. I saw that you reported this issue on the Blender bug tracker here: https://developer.blender.org/T67605

I would suggest attaching your .blend file to that issue so that the Blender developers can test this.

**Closed by rlguy** 2019-07-24 18:05 UTC

**Comment by chienMouille** [comment] 2019-07-24 18:06
great thanks a lot, and sorry for reporting too fast
