### ISSUE TITLE
problem on installing add on on a virtual machine

### ISSUE THREAD

**Issue by NewblenderUser** [rlguy/Blender-FLIP-Fluids#400] opened 2018-12-06 20:31 UTC
Just purchased the flip fluid pack.
Installed without problem on a laptop (windows 10 64 bits, blender 2.79)
failed to install on a cloud machine with windows 2012 server 64 bits under the same version of blender. 
read the issues reported here before, guess it  might be related to graphic card/driver since the cloud machine does not technically have a graphic card.  Any suggestions?

**Comment by rlguy** [comment] 2018-12-08 01:43
Hi NewblenderUser,

Thanks for the report! I am sorry to hear that you are running into problems installing the addon. We no longer require a GPU for the addon and have moved all calculations to run on the CPU, so this should not be the cause of the issue.

Are there any error messages when attempting to install the addon? Full error messages can be found by opening the Blender System Console (**Blender > Window > Toggle System Console**).

Would you be able to attach your Blender system info file? This file can help provide more information on your Blender install. (**Blender > Help > Save System Info**).

Best Regards,
Ryan

**Comment by NewblenderUser** [comment] 2018-12-10 15:50
Ryan
Thx for the response.  Yes, there is error msg. However, the error seems to prevent me even from performing Save System Info.  I tried on other remote terminals, flip fluid can be installed on 2 out 4 and failed on the other 2.   Can not save system info due to the same error.

<img width="893" alt="2018-11-06_-ai registration" src="https://user-images.githubusercontent.com/45671482/49743679-4c7fa700-fc69-11e8-90d0-a412bd30ae07.png">

**Comment by rlguy** [comment] 2018-12-10 18:23
Hi, thanks for attaching the error message!

This type of error can occur if Blender encounters a problem during addon installation. The error causes Blender to place addon files in an incorrect location which creates a conflict in Blender's user configuration. The cause for this error is unknown, but can be fixed.

In your addon installation directory there might be a file called **types.py**. The fix for this error is to delete this file if it exists (perhaps make a backup of this file just in case).

Example, on my system the file would be located in the following path: **C:\Users\ryanl\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\types.py**

Let me know if you find this file and if deleting it allows you to install the addon successfully. Note: you will need to restart Blender after making these changes.

Hope this helps,
Ryan

**Comment by NewblenderUser** [comment] 2018-12-10 18:59
Ryan
Thank you so much. The problem is resolved with the solution you provided.

**Comment by rlguy** [comment] 2018-12-10 20:07
Great! Glad to help.

**Closed by rlguy** 2018-12-10 20:07 UTC
