### ISSUE TITLE
I cant install this add-on. NO ERRORS!!!

### ISSUE THREAD

**Issue by Konstantin749** [rlguy/Blender-FLIP-Fluids#481] opened 2019-12-01 11:31 UTC
I wanted to install flip fluid, did everything according to the instructions. Blender wrote " Modules Installed () from 'G:\\Blender-FLIP-Fluids-master.zip' into 'C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\ \ Blender\\2.81\\scripts\ \ addons" ,and addon did not appear.(Yandex translator)

**Comment by rlguy** [comment] 2019-12-01 17:31
Duplicate of #474

**Closed by rlguy** 2019-12-01 17:31 UTC
Labels: duplicate, invalid
