### ISSUE TITLE
Error when trying to bake.

### ISSUE THREAD

**Issue by systemik** [rlguy/Blender-FLIP-Fluids#459] opened 2019-06-05 19:44 UTC
#### System Information

**Blender Version (including hash):** version: 2.80 (sub 60), branch: blender2.7, commit date: 2019-05-07 19:17, hash: 3dc9da3a74ee, type: Release
**FLIP Fluids Version:** 1.0.5 and 9.0.6.0
**Operating System:** MacOs Mojave
**CPU:** Intel core i5
**GFX:** Intel Iris
**RAM:** 16G

#### Describe the bug

I was having success. I've started to experiment with the Object mesh volume (meshing volume in surface parameters). This was working great but after few bakes, I can not bake anymore and get an error message every time.
I checked multiple files (which were working previously with no success.
I've removed addon, re-installed addon. Checked with the beta version as well but issue is still present.

#### To Reproduce

This is not related to blend file it seems.

#### Expected Behaviour

Baking should work

#### Actual Behaviour

Baking fail with error message and baking status stay at "exporting static data... 0%"

#### Screenshots

Error message:
Traceback (most recent call last):
  File "/Users/systemic/Library/Application Support/Blender/2.80/scripts/addons/flip_fluids_addon/operators/export_operators.py", line 145, in modal
    is_finished = self.mesh_exporter.update_export(self.export_step_time)
  File "/Users/systemic/Library/Application Support/Blender/2.80/scripts/addons/flip_fluids_addon/objects/flip_fluid_mesh_exporter.py", line 239, in update_export
    is_finished = self._update_static_export(step_time)
  File "/Users/systemic/Library/Application Support/Blender/2.80/scripts/addons/flip_fluids_addon/objects/flip_fluid_mesh_exporter.py", line 274, in _update_static_export
    tmesh = self._get_static_triangle_mesh_data(obj)
  File "/Users/systemic/Library/Application Support/Blender/2.80/scripts/addons/flip_fluids_addon/objects/flip_fluid_mesh_exporter.py", line 292, in _get_static_triangle_mesh_data
    return vcu.object_to_triangle_mesh(obj, obj.matrix_world)
  File "/Users/systemic/Library/Application Support/Blender/2.80/scripts/addons/flip_fluids_addon/utils/version_compatibility_utils.py", line 236, in object_to_triangle_mesh
    depsgraph = bpy.context.evaluated_depsgraph_get()
AttributeError: 'Context' object has no attribute 'evaluated_depsgraph_get'

location: <unknown location>:-1

**Comment by rlguy** [comment] 2019-06-05 19:47
Hi systemik,

This is a duplicate of issue #450. To fix this error, you will need to update to a more recent version of Blender 2.80: https://builder.blender.org/download/

- Ryan

**Closed by rlguy** 2019-06-05 19:47 UTC

**Comment by systemik** [comment] 2019-06-05 19:54
Really sorry. Missed this one.
Not sure why it failed to work suddenly but you're a star.
I've updated to latest beta and it works perfectly...
Fixing my issue after few minutes I've posted it is royal :-)
Thanks again.

**Comment by 1nash** [comment] 2021-07-28 22:18
Honestly im having the same problem  ans have tried to update my bleder  to 2.91 bit still it has failed to work flip still brings the same Error messege ........... Please help

**Comment by Allenxroot** [comment] 2021-08-05 11:33
same man this is happening with me too and im on the latest update of blender need help T.T

**Comment by rlguy** [comment] 2021-08-05 16:45
Hi, this error should only be possible in earlier versions of Blender 2.80 and a more recent installation of Blender is required to resolve this issue. Tip: when opening Blender, check the splash screen for the version number to verify that you are running the correct version:

![splash_screen](https://user-images.githubusercontent.com/4285191/128388819-c16ce46d-b990-41fd-a59c-027a1e25ec78.jpg)

Also, if using the most recent version of Blender (2.93), make sure that you are also running the latest version of the FLIP Fluids addon (v1.0.9b 06-APR-2021 or the current GitHub master) which adds compatibility for Blender 2.93.
