### ISSUE TITLE
Surface Tension estimated substeps not updated

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#497] opened 2020-05-29 16:08 UTC
#### System Information

**Blender Version (including hash):** version: 2.82 (sub 7), branch: master, commit date: 2020-03-12 05:06, hash: `rB375c7dc4caf4`
**FLIP Fluids Version:** 1.0.8a
**Operating System:** Windows 10
**CPU:** AMD A8 5600K
**GFX:**
**RAM:** 8 GB

#### Describe the bug

The Estimated substeps hint for surface tension does not correctly show the value of the substeps if the Speed parameter is animated.

#### To Reproduce

Create a domain, animate the Speed parameter (for example, from 0.1 to 2.0), go to any frame and you will see that the prompt does not change.

#### Expected Behaviour

It is necessary that the addon recount the value of substeps when changing the frame.

#### Actual Behaviour

The value is always the same, even if the Speed parameter are animated.

#### Screenshots

![speed_2](https://user-images.githubusercontent.com/7983249/83280726-b84c2b80-a1df-11ea-88b3-5b80ca22a9d4.jpg)
![speed_05](https://user-images.githubusercontent.com/7983249/83280738-bbdfb280-a1df-11ea-8ee6-d5f010d52864.jpg)

**Comment by rlguy** [comment] 2020-05-29 18:09
Hi PavelBlend,

Thanks for the report and letting me know about this!

The script that updates the substeps value is triggered whenever Blender 2.8 updates the scene in (depsgraph update). It looks like the problem is that a frame change is not triggering a scene update. 

In earlier versions of Blender, scene updates were very frequent, As Blender developed and became more efficient in later versions, the scene updates are less often and it looks like frame changes do not happen on a frame change. If you click somewhere in the viewport or change a simulation setting, this should trigger a scene update and the value should change.

I have fixed this bug by making sure the script is both triggered during a scene update and a frame change. This will be included int he next version release (v1.0.9).

\- Ryan

**Closed by rlguy** 2020-05-29 18:09 UTC
Labels: bug
