### ISSUE TITLE
Export Alembic

### ISSUE THREAD

**Issue by NovioK** [rlguy/Blender-FLIP-Fluids#358] opened 2018-07-18 12:00 UTC
Exporting an Alembic of a sim doesn't seem possible.
Am I missing something?

**Comment by rlguy** [comment] 2018-07-18 19:15
This is a duplicate of issue #47

See this document: https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Scene-Troubleshooting#export-to-alembic-cache-is-not-exporting-animated-meshes

This issue may also provide helpful information for rendering the Alembic cache: #352

Check out our [Technical Support Guidelines](https://github.com/rlguy/Blender-FLIP-Fluids/wiki/Technical-Support-Guidelines) for resources on how to use the issue tracker, report bugs, and scene issues. 

\- Ryan

**Closed by rlguy** 2018-07-18 19:15 UTC
Labels: duplicate
