### ISSUE TITLE
Conflict with Photographer Addon - The fluid simulation animation doesn't show

### ISSUE THREAD

**Issue by Oxervision** [rlguy/Blender-FLIP-Fluids#502] opened 2020-10-02 02:06 UTC
Hi,
I new in the use of Blender ( I come from SketchUp) and I'm probing a lot of addons.
 I downloaded the flip_fluids_addon-0.0.8a_demo_05_mar_2020 and the addon is fantastic, it works fine in Blender 283.6/2.90.1 & macOS 10.13.6. After days testing it, all worked fine, I installed the Photographer addon and when I push Play Animation, the Fluid Simulation is not showed, but if I push 'Sidebar > Flip Fluids > Reload Frame' button, this frame shows the simulation.

Regards,

Oxer

**Comment by rlguy** [comment] 2020-10-02 16:59
Hi Oxer,

Thanks for letting us know about the conflict! I just had a chance to test the Photographer addon but was unable to reproduce the conflict. Playback seems to be working as expect on my end testing with Windows and MacOS (10.13.6). I have a few questions that could help narrow down the issue:

I had downloaded installed the Photographer addon from this page: https://gumroad.com/l/FWQf

- Is this the same addon that you have installed? I have installed Photographer version 2.2.3:

![photographer_info](https://user-images.githubusercontent.com/4285191/94948812-cfa06b80-0494-11eb-86fe-aaf7d65c1c14.jpg)

- Does playback start working as expected if you disable the Photographer addon and restart Blender?
- Are you able to attach a simple .blend file that reproduces the issue (the simulation cache is not required)? This could help us check if it an issue with the .blend file. You can attach files by creating a .zip archive and attaching to this issue or by sending the file to support@flipfluids.com.
 
\- Ryan

**Comment by Oxervision** [comment] 2020-10-03 15:43
**1.** I use Photographer version 3.1.1, the v2.2.3 has not conlfict with Flip Fluids.
**2.** If I disable Photgrapher in User Preferences and I restar Blender, the simulation works fine wheh I play the animation.
**3.** The .blend file is very simple, a cube as domain and a cylinder as inflow.
[Fluid Test.blend.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/5321913/Fluid.Test.blend.zip)

**Comment by tm604** [comment] 2020-10-05 15:02
I'm seeing exactly the same symptoms, Photographer 3.3.3 with all versions of FLIP Fluids (stable 1.0.5a from March, and experimental builds up to 30th September).

Happens on Blender 2.83.7 LTS and 2.90.1, everything's back to normal after disabling Photographer.

(thanks @Oxervision for raising this, saved me a lot of time in tracking down what was going on!)

**Comment by rlguy** [comment] 2020-10-05 15:37
Thanks for the updates and added info!

I just had a chance to check out Photographer 3 from the Blender Market. I tested the latest version (v3.3.10) released Oct 3rd, 2020, but was not able to reproduce the issue. Does updating Photographer 3 to the latest version fix this issue on your sides?

I came across [this post from the author (Sept 27th, 2020)](https://blenderartists.org/t/photographer-camera-exposure-white-balance-autofocus-and-physical-lights/1101721/544) that could have been a potential fix to the issue since v3.3.8:

> An artist reported some compatibility issues with other add-ons, such as the sun position add-on. I prefer not to release too many versions so quickly, but I think this a important enough fix that requires an update.
>
>New version 3.3.8:
>- Fix animation issues that could affect other add-ons.

Let me know if the issue still persists in the latest version and I can look further into this and contact the author.

\- Ryan

**Comment by tm604** [comment] 2020-10-05 15:44
Thanks for the quick response - yes, the latest version 3.3.10 does indeed fix the problem for me, and the author confirmed as well that it's expected to be fixed by that release.

**Comment by rlguy** [comment] 2020-10-05 16:33
Excellent! Great to hear that this issue has been resolved in later versions of the Photographer addon.

I'll be closing this issue as resolved, but if you run into any more conflicts with this addon, let us know and we can re-open the issue.

\- Ryan

**Closed by rlguy** 2020-10-05 16:33 UTC
