### ISSUE TITLE
Incorrect liquid surface scale

### ISSUE THREAD

**Issue by PavelBlend** [rlguy/Blender-FLIP-Fluids#414] opened 2019-01-23 13:16 UTC
#### System Information

**Blender Version: 2.79b f4dc9f9d68b**
**FLIP Fluids Version: 9.0.5**
**Operating System: Windows 7 64 bit**
**CPU: AMD A8 5600K 3.60GHz 4 Core**
**GFX: None**
**RAM: 8 GB**

#### Describe the bug

The surface of the fluid does not match the debug particles. This is due to the fact that the scale of the surface is not correct.

#### To Reproduce

Open the blend file and run the simulation.
[surface_scale_bug.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2787401/surface_scale_bug.zip)

#### Expected Behaviour

The scale of the surface must be 1.0

#### Actual Behaviour

Liquid surface scale is not 1.0

#### Screenshots

![222](https://user-images.githubusercontent.com/7983249/51608934-e35aa700-1f29-11e9-8717-70229154359d.jpg)

**Comment by rlguy** [comment] 2019-01-23 20:54
Hey PavelBlend,

Thanks for the report! I was able to reproduce this error.

This bug is caused by a rounding/precision error when calculating the resolution within the addon. In your scene, the resolution is set to 50. The addon was calculating the resolution to be 50.00000111758712, which was rounded up to 51. This caused the fluid mesh to be scaled up slightly to match the resolution of 51.

This bug has been fixed and will be included in the next update which will be available either this Friday (Jan 25th) or next Friday (Feb 1st).

\- Ryan

**Comment by PavelBlend** [comment] 2019-02-02 19:06
It seems this problem has remained in version 9.0.5.3:
![01](https://user-images.githubusercontent.com/7983249/52168101-a31fd380-2736-11e9-9180-d7c0ae6fa3be.jpg)
[test_scene_01.zip](https://github.com/rlguy/Blender-FLIP-Fluids/files/2824751/test_scene_01.zip)

**Comment by rlguy** [comment] 2019-02-05 21:01
Hey PavelBlend,

Thanks for letting me know! I just had a chance to check this out and it looks like this is a result of bad code design. I'm calculating the resolution differently in different areas of the addon/simulator. This is leading to different resolution values which is causing incorrect scale:

![inconsistent_grid](https://user-images.githubusercontent.com/4285191/52303668-72fa4f80-2945-11e9-99c2-4fb476ae5314.jpg)

I'll redesign how the addon/simulator handles resolution and grid dimension calculations so that that can be fixed in the next version.

\- Ryan

**Comment by rlguy** [comment] 2019-02-07 23:02
Alright, hope this is all fixed now! I have update the way we calculate grid dimensions/resolution to be the same between the UI resolution, debug display, simulation, and mesh scaling. This fix will be included in the next version update (1.0.5)

**Closed by rlguy** 2019-02-07 23:02 UTC
Labels: bug
