### ISSUE TITLE
target object for fluid inflow objects not deleted

### ISSUE THREAD

**Issue by lumpynose** [rlguy/Blender-FLIP-Fluids#405] opened 2018-12-14 00:07 UTC
#### System Information

**Blender Version (including hash): 2.79b f4dcdf9d68b**
**FLIP Fluids Version: 9.05 experimental 19-nov-2018**
**Operating System: windows 10**
**CPU: intel**
**GFX: gtx 1070**
**RAM: 16gb**

#### Describe the bug

If you add a Fluid object and make it the Target Object for a fluid Inflow object, when you delete the Fluid object (I right clicked on it in the Outliner and deleted it) it's not deleted.  It's removed from the 3d view but when you run the simulation again its fluid is generated again.  You can also see it in the Outliner under Blender File and Data-Blocks under Objects.  Although it's not displayed in the All Scenes list in the Outliner. The Target Object could also be an Empty, or probably anything.

After you delete the object from the Inflow's Target Object field then it goes away.

#### To Reproduce

Create an Inflow object, make its Target Object be some other object, then delete that other object and look for the Target Object in the Outliner under Blender File -> Objects.

#### Expected Behaviour

If you add an Empty, then add an Icosphere and a Cube, then add a Rigid Body constraint to the Empty then make the Icosphere its Object 1 and the Cube its Object 2, you can then delete either or both of them and they're deleted (you may need to save the blend file and then quit and reopen it).  With Flip Fluids the expected behavior would be for the Inflow's Target Object to be fully deleted without first needing to delete from the Inflow panel's Target Object field.

#### Actual Behaviour

The Inflow's Target Object is only partially deleted.

#### Screenshots

https://imgur.com/a/bG6biuS

**Comment by rlguy** [comment] 2018-12-14 00:32
Hi lumpynose,

Thanks for the report! That is interesting behaviour and I did not think of this case. The problem is that the addon is looking through all of the objects in the .blend file data when it should actually only be looking through the objects in the scene. This should be easy to resolve, and I'll update this issue when it's fixed!

\- Ryan

**Comment by rlguy** [comment] 2018-12-25 01:38
This has been fixed and will be included in the next experimental version (9.0.5.2)!

**Closed by rlguy** 2018-12-25 01:38 UTC
Labels: bug
