### ISSUE TITLE
Flip fluids error When baking

### ISSUE THREAD

**Issue by thefudgeishot** [rlguy/Blender-FLIP-Fluids#464] opened 2019-07-10 04:26 UTC
#### System Information

**Blender Version: 2.8:**
**FLIP Fluids Version: 1.0.5**
**Operating System: Windows 10**
**CPU: Amd Ryzen 5 2600x Six-Core Processor**
**GFX: Rtx 2070**
**RAM: 16gb**

#### Describe the bug

Whenever i try to bake my simulation i get an error. I have uninstalled all other addons and i am still receiving the error.

#### To Reproduce

Clicking Bake in the domain.

#### Expected Behaviour

The simulation to bake.

#### Actual Behaviour

Pops out an error and sits at Exporting static data... 0.0%

#### Screenshots
![Flip Fluids Error](https://user-images.githubusercontent.com/33798627/60940403-ef86c500-a30d-11e9-9ed9-03b8757c728d.png)

**Comment by thefudgeishot** [comment] 2019-07-10 04:29
System Info
[system-info.txt](https://github.com/rlguy/Blender-FLIP-Fluids/files/3375726/system-info.txt)

**Comment by rlguy** [comment] 2019-07-10 04:44
Duplicate of #450. The quick fix is to update your install of Blender 2.80 to a newer version.

**Closed by rlguy** 2019-07-10 04:44 UTC
