### ISSUE TITLE
Missing triangles/holes in surface mesh (fixed, update to 1.0.4a)

### ISSUE THREAD

**Issue by niklassjogren** [rlguy/Blender-FLIP-Fluids#372] opened 2018-08-12 18:22 UTC
#### System Information

**Blender Version (including hash):**
Blender 2.79b Hash:f4dc9f9d68b
**FLIP Fluids Version:**
1.0.4
**Operating System:**
Windows 10
**CPU:**
Intel i7-6850K @ 3.60GHx
**GFX:**
Nvidia GTX 1070
Nvidia GTX 970
Driver 398.36
**RAM:**
32GB

#### Describe the bug

I do see a lot of holes, missing polygons (non-manifold geometry) that I didn't notice in earlier versions?

#### To Reproduce

Imported geometry (Alembic), made a domain and fluid in Blender, tried the Coffee preset for settings!

#### Expected Behaviour

No missing polygons!

#### Actual Behaviour

some missing polygons in the fluid mesh, see screenshots!

#### Screenshots

![image](https://user-images.githubusercontent.com/7673361/44005003-4ea61a88-9e6c-11e8-9cee-28a3217b5da2.png)
After a Shift-Ctrl-Alt-M (non-manifold geometry):
![image](https://user-images.githubusercontent.com/7673361/44005039-f1f2c16e-9e6c-11e8-8ce0-32bdf4fac7ce.png)

**Comment by rlguy** [comment] 2018-08-12 18:26
Hey niklassjogren,

Thanks for letting me know abut this! This could be an issue new particle mesher in 1.0.4. Would you be able to attach a .blend file that reproduces this issue?

\- Ryan

**Comment by niklassjogren** [comment] 2018-08-12 23:41
Yes of course! I uploaded them and shared them from my dropbox, the .zip also includes all the files including the Cache if needed!
https://www.dropbox.com/sh/e4fkakhc1tzdexw/AABaHc76Ntpe653OEwdsDdZNa?dl=0

/niklas

**Comment by rlguy** [comment] 2018-08-24 02:11
This issue has been fixed and will be included in a patched version **v1.0.4a** that will be available August 24th, 2018. It is highly advised to upgrade to the patched version as this update will fix some major bugs within the particle mesher (#376, #377).

![issue_missing_triangles](https://user-images.githubusercontent.com/4285191/44561028-67083180-a707-11e8-98ca-ef93fb9a9724.jpg)

This bug was caused by numerical precision errors. The mesher calculates the surface mesh in chunks and then '_welds_' the pieces together to join the vertices/edges. When triangles become small, there can be numerical errors in CPU calculations due to the finite amount of precision that a 32-bit number stores. These precision errors caused vertices not to line up properly and they would not become '_welded_' together resulting in holes within the surface mesh. This issue has been fixed by internally scaling the mesh to an appropriate size so that the CPU can handle calculations accurately while joining mesh chunks.

**Comment by niklassjogren** [comment] 2018-08-24 12:30
Sounds great, awesome work!

**Closed** 2018-08-28 16:11 UTC
Labels: bug
